name: taraf_store
description: Taraf Store - A professional WebView Flutter application.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.13.0
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.11
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"
  android_12:
    image: "assets/images/splash.png"
    color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
